export const CITIES = [
  "Casablanca",
  "Rabat",
  "Salé",
  "Marrakech",
  "Fès",
  "Tanger",
  "Agadir",
  "Meknès",
  "Oujda",
  "Kénitra",
  "Tétouan",
  "Laâyoune",
  "Dakhla",
  "Nador",
  "Al Hoceïma",
  "Beni Mellal",
  "Khénifra",
  "Settat",
  "Berrechid",
  "Mohammadia",
  "El Jadida",
  "Safi",
  "Essaouira",
  "Ouarzazate",
  "Errachidia",
  "Guelmim",
  "Taza",
  "Ifrane",
  "Khémisset",
  "Témara",
];

export const NEIGHBORHOODS_BY_CITY: Record<string, string[]> = {
  Rabat: [
    "Agdal",
    "Hay Ryad",
    "CYM",
    "Souissi",
    "Yacoub El Mansour",
    "Hassan",
    "Océan",
    "Aviation",
    "Diour Jamaa",
    "Centre-Ville",
  ],
  Casablanca: [
    "Maarif",
    "Anfa",
    "Bourgogne",
    "Gauthier",
    "Ain Diab",
    "Hay Hassani",
    "Sidi Maarouf",
    "Racine",
    "Centre-Ville",
  ],
  Marrakech: ["Guéliz", "Hivernage", "Médina", "Hay Mohammadi", "M'hamid"],
  Fès: ["Fès El Bali", "Fès El Jedid", "Agdal", "Narjiss", "Route de Séfrou"],
  Tanger: ["Centre-Ville", "Malabata", "Béni Makada", "Marshan"],
  Agadir: ["Talborjt", "Hay Mohammadi", "Charaf", "Dakhla"],
  Meknès: ["Centre-Ville", "Hamria", "Ismaïlia", "Marjane"],
  Oujda: ["Centre-Ville", "Sidi Yahya", "Hay Qods"],
  Kénitra: ["Centre-Ville", "Saknia", "Bir Rami"],
  Tétouan: ["Centre-Ville", "Martil", "M'diq"],
  Salé: ["Bettana", "Tabriquet", "Hay Salam"],
  Témara: ["Centre-Ville", "Hay Islan", "Hay Al Menzah"],
  Mohammadia: ["Centre-Ville", "Hay Lalla Aicha", "Sidi Moumen"],
  "El Jadida": ["Centre-Ville", "Azemmour", "Hay Hassani"],
  Safi: ["Centre-Ville", "Hay Mohammadi", "Sidi Bouzid"],
  Essaouira: ["Médina", "Centre-Ville", "Diabat"],
  Nador: ["Centre-Ville", "Hay Lalla Fatima", "Beni Nsar"],
  "Al Hoceïma": ["Centre-Ville", "Ajdir", "Hay Hammou"],
  "Beni Mellal": ["Centre-Ville", "Hay Ismaïlia", "Ain Asserdoun"],
  Settat: ["Centre-Ville", "Hay Mohammadi"],
  Laâyoune: ["Centre-Ville", "Hay Chabab", "Hay Salam"],
  Dakhla: ["Centre-Ville", "Hay Wahda"],
  Ouarzazate: ["Centre-Ville", "Hay Hassani", "Tabount"],
  Taza: ["Centre-Ville", "Hay Lalla Aicha"],
  Guelmim: ["Centre-Ville", "Hay Salam"],
};

export const SPECIALTIES = [
  "Implants",
  "Orthodontie",
  "Pédiatrie",
  "Esthétique",
  "Chirurgie",
  "Parodontologie",
  "Endodontie",
  "Prothèse",
  "Blanchiment",
];
