export const CITIES = [
  "Rabat",
  "Casablanca",
  "Marrakech",
  "Fès",
  "Tanger",
  "Agadir",
  "Meknès",
  "Oujda",
  "Kénitra",
  "Tétouan",
  "Salé",
];

export const NEIGHBORHOODS_BY_CITY: Record<string, string[]> = {
  Rabat: [
    "Agdal",
    "Hay Ryad",
    "CYM",
    "Souissi",
    "Yacoub El Mansour",
    "Hassan",
    "Océan",
    "Aviation",
    "Diour Jamaa",
    "Centre-Ville",
  ],
  Casablanca: [
    "Maarif",
    "Anfa",
    "Bourgogne",
    "Gauthier",
    "Ain Diab",
    "Hay Hassani",
    "Sidi Maarouf",
    "Racine",
    "Centre-Ville",
  ],
  Marrakech: ["Guéliz", "Hivernage", "Médina", "Hay Mohammadi", "M'hamid"],
  Fès: ["Fès El Bali", "Fès El Jedid", "Agdal", "Narjiss", "Route de Séfrou"],
  Tanger: ["Centre-Ville", "Malabata", "Béni Makada", "Marshan"],
  Agadir: ["Talborjt", "Hay Mohammadi", "Charaf", "Dakhla"],
  Meknès: ["Centre-Ville", "Hamria", "Ismaïlia", "Marjane"],
  Oujda: ["Centre-Ville", "Sidi Yahya", "Hay Qods"],
  Kénitra: ["Centre-Ville", "Saknia", "Bir Rami"],
  Tétouan: ["Centre-Ville", "Martil", "M'diq"],
  Salé: ["Bettana", "Tabriquet", "Hay Salam"],
};

export const SPECIALTIES = [
  "Implants",
  "Orthodontie",
  "Pédiatrie",
  "Esthétique",
  "Chirurgie",
  "Parodontologie",
  "Endodontie",
  "Prothèse",
  "Blanchiment",
];
